-- Generated by http://csv2sql.com online CSV to SQL converter

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Afghanistan","Islamic State of Afghanistan","Kabul","AFN","Afghani","93",".af");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Albania","Republic of Albania","Tirana","ALL","Lek","355",".al");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Algeria","People's Democratic Republic of Algeria","Algiers","DZD","Dinar","213",".dz");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Andorra","Principality of Andorra","Andorra la Vella","EUR","Euro","376",".ad");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Angola","Republic of Angola","Luanda","AOA","Kwanza","244",".ao");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Antigua and Barbuda","","Saint John's","XCD","Dollar","1-268",".ag");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Argentina","Argentine Republic","Buenos Aires","ARS","Peso","54",".ar");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Armenia","Republic of Armenia","Yerevan","AMD","Dram","374",".am");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Australia","Commonwealth of Australia","Canberra","AUD","Dollar","61",".au");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Austria","Republic of Austria","Vienna","EUR","Euro","43",".at");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Azerbaijan","Republic of Azerbaijan","Baku","AZN","Manat","994",".az");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Bahamas, The","Commonwealth of The Bahamas","Nassau","BSD","Dollar","1-242",".bs");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Bahrain","Kingdom of Bahrain","Manama","BHD","Dinar","973",".bh");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Bangladesh","People's Republic of Bangladesh","Dhaka","BDT","Taka","880",".bd");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Barbados","","Bridgetown","BBD","Dollar","1-246",".bb");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Belarus","Republic of Belarus","Minsk","BYR","Ruble","375",".by");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Belgium","Kingdom of Belgium","Brussels","EUR","Euro","32",".be");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Belize","","Belmopan","BZD","Dollar","501",".bz");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Benin","Republic of Benin","Porto-Novo","XOF","Franc","229",".bj");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Bhutan","Kingdom of Bhutan","Thimphu","BTN","Ngultrum","975",".bt");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Bolivia","Republic of Bolivia","La Paz (administrative/legislative) and Sucre (judical)","BOB","Boliviano","591",".bo");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Bosnia and Herzegovina","","Sarajevo","BAM","Marka","387",".ba");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Botswana","Republic of Botswana","Gaborone","BWP","Pula","267",".bw");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Brazil","Federative Republic of Brazil","Brasilia","BRL","Real","55",".br");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Brunei","Negara Brunei Darussalam","Bandar Seri Begawan","BND","Dollar","673",".bn");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Bulgaria","Republic of Bulgaria","Sofia","BGN","Lev","359",".bg");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Burkina Faso","","Ouagadougou","XOF","Franc","226",".bf");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Burundi","Republic of Burundi","Bujumbura","BIF","Franc","257",".bi");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Cambodia","Kingdom of Cambodia","Phnom Penh","KHR","Riels","855",".kh");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Cameroon","Republic of Cameroon","Yaounde","XAF","Franc","237",".cm");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Canada","","Ottawa","CAD","Dollar","1",".ca");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Cape Verde","Republic of Cape Verde","Praia","CVE","Escudo","238",".cv");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Central African Republic","","Bangui","XAF","Franc","236",".cf");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Chad","Republic of Chad","N'Djamena","XAF","Franc","235",".td");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Chile","Republic of Chile","Santiago (administrative/judical) and Valparaiso (legislative)","CLP","Peso","56",".cl");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("China, People's Republic of","People's Republic of China","Beijing","CNY","Yuan Renminbi","86",".cn");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Colombia","Republic of Colombia","Bogota","COP","Peso","57",".co");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Comoros","Union of Comoros","Moroni","KMF","Franc","269",".km");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Congo, Democratic Republic of the (Congo ? Kinshasa)","Democratic Republic of the Congo","Kinshasa","CDF","Franc","243",".cd");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Congo, Republic of the (Congo ? Brazzaville)","Republic of the Congo","Brazzaville","XAF","Franc","242",".cg");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Costa Rica","Republic of Costa Rica","San Jose","CRC","Colon","506",".cr");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Cote d'Ivoire (Ivory Coast)","Republic of Cote d'Ivoire","Yamoussoukro","XOF","Franc","225",".ci");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Croatia","Republic of Croatia","Zagreb","HRK","Kuna","385",".hr");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Cuba","Republic of Cuba","Havana","CUP","Peso","53",".cu");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Cyprus","Republic of Cyprus","Nicosia","CYP","Pound","357",".cy");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Czech Republic","","Prague","CZK","Koruna","420",".cz");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Denmark","Kingdom of Denmark","Copenhagen","DKK","Krone","45",".dk");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Djibouti","Republic of Djibouti","Djibouti","DJF","Franc","253",".dj");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Dominica","Commonwealth of Dominica","Roseau","XCD","Dollar","1-767",".dm");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Dominican Republic","","Santo Domingo","DOP","Peso","1-809 and 1-829",".do");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Ecuador","Republic of Ecuador","Quito","USD","Dollar","593",".ec");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Egypt","Arab Republic of Egypt","Cairo","EGP","Pound","20",".eg");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("El Salvador","Republic of El Salvador","San Salvador","USD","Dollar","503",".sv");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Equatorial Guinea","Republic of Equatorial Guinea","Malabo","XAF","Franc","240",".gq");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Eritrea","State of Eritrea","Asmara","ERN","Nakfa","291",".er");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Estonia","Republic of Estonia","Tallinn","EEK","Kroon","372",".ee");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Ethiopia","Federal Democratic Republic of Ethiopia","Addis Ababa","ETB","Birr","251",".et");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Fiji","Republic of the Fiji Islands","Suva","FJD","Dollar","679",".fj");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Finland","Republic of Finland","Helsinki","EUR","Euro","358",".fi");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("France","French Republic","Paris","EUR","Euro","33",".fr");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Gabon","Gabonese Republic","Libreville","XAF","Franc","241",".ga");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Gambia, The","Republic of The Gambia","Banjul","GMD","Dalasi","220",".gm");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Georgia","Republic of Georgia","Tbilisi","GEL","Lari","995",".ge");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Germany","Federal Republic of Germany","Berlin","EUR","Euro","49",".de");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Ghana","Republic of Ghana","Accra","GHS","Cedi","233",".gh");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Greece","Hellenic Republic","Athens","EUR","Euro","30",".gr");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Grenada","","Saint George's","XCD","Dollar","1-473",".gd");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Guatemala","Republic of Guatemala","Guatemala","GTQ","Quetzal","502",".gt");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Guinea","Republic of Guinea","Conakry","GNF","Franc","224",".gn");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Guinea-Bissau","Republic of Guinea-Bissau","Bissau","XOF","Franc","245",".gw");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Guyana","Co-operative Republic of Guyana","Georgetown","GYD","Dollar","592",".gy");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Haiti","Republic of Haiti","Port-au-Prince","HTG","Gourde","509",".ht");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Honduras","Republic of Honduras","Tegucigalpa","HNL","Lempira","504",".hn");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Hungary","Republic of Hungary","Budapest","HUF","Forint","36",".hu");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Iceland","Republic of Iceland","Reykjavik","ISK","Krona","354",".is");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("India","Republic of India","New Delhi","INR","Rupee","91",".in");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Indonesia","Republic of Indonesia","Jakarta","IDR","Rupiah","62",".id");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Iran","Islamic Republic of Iran","Tehran","IRR","Rial","98",".ir");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Iraq","Republic of Iraq","Baghdad","IQD","Dinar","964",".iq");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Ireland","","Dublin","EUR","Euro","353",".ie");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Israel","State of Israel","Jerusalem","ILS","Shekel","972",".il");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Italy","Italian Republic","Rome","EUR","Euro","39",".it");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Jamaica","","Kingston","JMD","Dollar","1-876",".jm");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Japan","","Tokyo","JPY","Yen","81",".jp");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Jordan","Hashemite Kingdom of Jordan","Amman","JOD","Dinar","962",".jo");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Kazakhstan","Republic of Kazakhstan","Astana","KZT","Tenge","7",".kz");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Kenya","Republic of Kenya","Nairobi","KES","Shilling","254",".ke");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Kiribati","Republic of Kiribati","Tarawa","AUD","Dollar","686",".ki");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Korea, Democratic People's Republic of (North Korea)","Democratic People's Republic of Korea","Pyongyang","KPW","Won","850",".kp");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Korea, Republic of  (South Korea)","Republic of Korea","Seoul","KRW","Won","82",".kr");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Kuwait","State of Kuwait","Kuwait","KWD","Dinar","965",".kw");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Kyrgyzstan","Kyrgyz Republic","Bishkek","KGS","Som","996",".kg");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Laos","Lao People's Democratic Republic","Vientiane","LAK","Kip","856",".la");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Latvia","Republic of Latvia","Riga","LVL","Lat","371",".lv");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Lebanon","Lebanese Republic","Beirut","LBP","Pound","961",".lb");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Lesotho","Kingdom of Lesotho","Maseru","LSL","Loti","266",".ls");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Liberia","Republic of Liberia","Monrovia","LRD","Dollar","231",".lr");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Libya","Great Socialist People's Libyan Arab Jamahiriya","Tripoli","LYD","Dinar","218",".ly");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Liechtenstein","Principality of Liechtenstein","Vaduz","CHF","Franc","423",".li");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Lithuania","Republic of Lithuania","Vilnius","LTL","Litas","370",".lt");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Luxembourg","Grand Duchy of Luxembourg","Luxembourg","EUR","Euro","352",".lu");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Macedonia","Republic of Macedonia","Skopje","MKD","Denar","389",".mk");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Madagascar","Republic of Madagascar","Antananarivo","MGA","Ariary","261",".mg");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Malawi","Republic of Malawi","Lilongwe","MWK","Kwacha","265",".mw");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Malaysia","","Kuala Lumpur (legislative/judical) and Putrajaya (administrative)","MYR","Ringgit","60",".my");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Maldives","Republic of Maldives","Male","MVR","Rufiyaa","960",".mv");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Mali","Republic of Mali","Bamako","XOF","Franc","223",".ml");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Malta","Republic of Malta","Valletta","MTL","Lira","356",".mt");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Marshall Islands","Republic of the Marshall Islands","Majuro","USD","Dollar","692",".mh");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Mauritania","Islamic Republic of Mauritania","Nouakchott","MRO","Ouguiya","222",".mr");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Mauritius","Republic of Mauritius","Port Louis","MUR","Rupee","230",".mu");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Mexico","United Mexican States","Mexico","MXN","Peso","52",".mx");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Micronesia","Federated States of Micronesia","Palikir","USD","Dollar","691",".fm");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Moldova","Republic of Moldova","Chisinau","MDL","Leu","373",".md");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Monaco","Principality of Monaco","Monaco","EUR","Euro","377",".mc");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Mongolia","","Ulaanbaatar","MNT","Tugrik","976",".mn");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Montenegro","Republic of Montenegro","Podgorica","EUR","Euro","382",".me and .yu");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Morocco","Kingdom of Morocco","Rabat","MAD","Dirham","212",".ma");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Mozambique","Republic of Mozambique","Maputo","MZM","Meticail","258",".mz");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Myanmar (Burma)","Union of Myanmar","Naypyidaw","MMK","Kyat","95",".mm");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Namibia","Republic of Namibia","Windhoek","NAD","Dollar","264",".na");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Nauru","Republic of Nauru","Yaren","AUD","Dollar","674",".nr");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Nepal","","Kathmandu","NPR","Rupee","977",".np");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Netherlands","Kingdom of the Netherlands","Amsterdam (administrative) and The Hague (legislative/judical)","EUR","Euro","31",".nl");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("New Zealand","","Wellington","NZD","Dollar","64",".nz");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Nicaragua","Republic of Nicaragua","Managua","NIO","Cordoba","505",".ni");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Niger","Republic of Niger","Niamey","XOF","Franc","227",".ne");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Nigeria","Federal Republic of Nigeria","Abuja","NGN","Naira","234",".ng");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Norway","Kingdom of Norway","Oslo","NOK","Krone","47",".no");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Oman","Sultanate of Oman","Muscat","OMR","Rial","968",".om");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Pakistan","Islamic Republic of Pakistan","Islamabad","PKR","Rupee","92",".pk");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Palau","Republic of Palau","Melekeok","USD","Dollar","680",".pw");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Panama","Republic of Panama","Panama","PAB","Balboa","507",".pa");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Papua New Guinea","Independent State of Papua New Guinea","Port Moresby","PGK","Kina","675",".pg");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Paraguay","Republic of Paraguay","Asuncion","PYG","Guarani","595",".py");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Peru","Republic of Peru","Lima","PEN","Sol","51",".pe");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Philippines","Republic of the Philippines","Manila","PHP","Peso","63",".ph");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Poland","Republic of Poland","Warsaw","PLN","Zloty","48",".pl");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Portugal","Portuguese Republic","Lisbon","EUR","Euro","351",".pt");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Qatar","State of Qatar","Doha","QAR","Rial","974",".qa");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Romania","","Bucharest","RON","Leu","40",".ro");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Russia","Russian Federation","Moscow","RUB","Ruble","7",".ru and .su");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Rwanda","Republic of Rwanda","Kigali","RWF","Franc","250",".rw");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Saint Kitts and Nevis","Federation of Saint Kitts and Nevis","Basseterre","XCD","Dollar","1-869",".kn");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Saint Lucia","","Castries","XCD","Dollar","1-758",".lc");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Saint Vincent and the Grenadines","","Kingstown","XCD","Dollar","1-784",".vc");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Samoa","Independent State of Samoa","Apia","WST","Tala","685",".ws");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("San Marino","Republic of San Marino","San Marino","EUR","Euro","378",".sm");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Sao Tome and Principe","Democratic Republic of Sao Tome and Principe","Sao Tome","STD","Dobra","239",".st");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Saudi Arabia","Kingdom of Saudi Arabia","Riyadh","SAR","Rial","966",".sa");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Senegal","Republic of Senegal","Dakar","XOF","Franc","221",".sn");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Serbia","Republic of Serbia","Belgrade","RSD","Dinar","381",".rs and .yu");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Seychelles","Republic of Seychelles","Victoria","SCR","Rupee","248",".sc");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Sierra Leone","Republic of Sierra Leone","Freetown","SLL","Leone","232",".sl");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Singapore","Republic of Singapore","Singapore","SGD","Dollar","65",".sg");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Slovakia","Slovak Republic","Bratislava","SKK","Koruna","421",".sk");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Slovenia","Republic of Slovenia","Ljubljana","EUR","Euro","386",".si");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Solomon Islands","","Honiara","SBD","Dollar","677",".sb");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Somalia","","Mogadishu","SOS","Shilling","252",".so");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("South Africa","Republic of South Africa","Pretoria (administrative), Cape Town (legislative), and Bloemfontein (judical)","ZAR","Rand","27",".za");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Spain","Kingdom of Spain","Madrid","EUR","Euro","34",".es");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Sri Lanka","Democratic Socialist Republic of Sri Lanka","Colombo (administrative/judical) and Sri Jayewardenepura Kotte (legislative)","LKR","Rupee","94",".lk");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Sudan","Republic of the Sudan","Khartoum","SDG","Pound","249",".sd");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Suriname","Republic of Suriname","Paramaribo","SRD","Dollar","597",".sr");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Swaziland","Kingdom of Swaziland","Mbabane (administrative) and Lobamba (legislative)","SZL","Lilangeni","268",".sz");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Sweden","Kingdom of Sweden","Stockholm","SEK","Kronoa","46",".se");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Switzerland","Swiss Confederation","Bern","CHF","Franc","41",".ch");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Syria","Syrian Arab Republic","Damascus","SYP","Pound","963",".sy");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Tajikistan","Republic of Tajikistan","Dushanbe","TJS","Somoni","992",".tj");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Tanzania","United Republic of Tanzania","Dar es Salaam (administrative/judical) and Dodoma (legislative)","TZS","Shilling","255",".tz");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Thailand","Kingdom of Thailand","Bangkok","THB","Baht","66",".th");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Timor-Leste (East Timor)","Democratic Republic of Timor-Leste","Dili","USD","Dollar","670",".tp and .tl");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Togo","Togolese Republic","Lome","XOF","Franc","228",".tg");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Tonga","Kingdom of Tonga","Nuku'alofa","TOP","Pa'anga","676",".to");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Trinidad and Tobago","Republic of Trinidad and Tobago","Port-of-Spain","TTD","Dollar","1-868",".tt");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Tunisia","Tunisian Republic","Tunis","TND","Dinar","216",".tn");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Turkey","Republic of Turkey","Ankara","TRY","Lira","90",".tr");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Turkmenistan","","Ashgabat","TMM","Manat","993",".tm");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Tuvalu","","Funafuti","AUD","Dollar","688",".tv");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Uganda","Republic of Uganda","Kampala","UGX","Shilling","256",".ug");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Ukraine","","Kiev","UAH","Hryvnia","380",".ua");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("United Arab Emirates","United Arab Emirates","Abu Dhabi","AED","Dirham","971",".ae");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("United Kingdom","United Kingdom of Great Britain and Northern Ireland","London","GBP","Pound","44",".uk");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("United States","United States of America","Washington","USD","Dollar","1",".us");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Uruguay","Oriental Republic of Uruguay","Montevideo","UYU","Peso","598",".uy");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Uzbekistan","Republic of Uzbekistan","Tashkent","UZS","Som","998",".uz");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Vanuatu","Republic of Vanuatu","Port-Vila","VUV","Vatu","678",".vu");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Vatican City","State of the Vatican City","Vatican City","EUR","Euro","379",".va");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Venezuela","Bolivarian Republic of Venezuela","Caracas","VEB","Bolivar","58",".ve");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Vietnam","Socialist Republic of Vietnam","Hanoi","VND","Dong","84",".vn");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Yemen","Republic of Yemen","Sanaa","YER","Rial","967",".ye");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Zambia","Republic of Zambia","Lusaka","ZMK","Kwacha","260",".zm");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Zimbabwe","Republic of Zimbabwe","Harare","ZWD","Dollar","263",".zw");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Abkhazia","Republic of Abkhazia","Sokhumi","RUB","Ruble","995",".ge");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("China, Republic of (Taiwan)","Republic of China","Taipei","TWD","Dollar","886",".tw");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Nagorno-Karabakh","Nagorno-Karabakh Republic","Stepanakert","AMD","Dram","277",".az");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Northern Cyprus","Turkish Republic of Northern Cyprus","Nicosia","TRY","Lira","90-392",".nc.tr");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Pridnestrovie (Transnistria)","Pridnestrovian Moldavian Republic","Tiraspol","","Ruple","373-533",".md");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Somaliland","Republic of Somaliland","Hargeisa","","Shilling","252",".so");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("South Ossetia","Republic of South Ossetia","Tskhinvali","RUB and GEL","Ruble and Lari","995",".ge");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Ashmore and Cartier Islands","Territory of Ashmore and Cartier Islands","","","","",".au");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Christmas Island","Territory of Christmas Island","The Settlement (Flying Fish Cove)","AUD","Dollar","61",".cx");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Cocos (Keeling) Islands","Territory of Cocos (Keeling) Islands","West Island","AUD","Dollar","61",".cc");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Coral Sea Islands","Coral Sea Islands Territory","","","","",".au");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Heard Island and McDonald Islands","Territory of Heard Island and McDonald Islands","","","","",".hm");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Norfolk Island","Territory of Norfolk Island","Kingston","AUD","Dollar","672",".nf");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("New Caledonia","","Noumea","XPF","Franc","687",".nc");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("French Polynesia","Overseas Country of French Polynesia","Papeete","XPF","Franc","689",".pf");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Mayotte","Departmental Collectivity of Mayotte","Mamoudzou","EUR","Euro","262",".yt");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Saint Barthelemy","Collectivity of Saint Barthelemy","Gustavia","EUR","Euro","590",".gp");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Saint Martin","Collectivity of Saint Martin","Marigot","EUR","Euro","590",".gp");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Saint Pierre and Miquelon","Territorial Collectivity of Saint Pierre and Miquelon","Saint-Pierre","EUR","Euro","508",".pm");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Wallis and Futuna","Collectivity of the Wallis and Futuna Islands","Mata'utu","XPF","Franc","681",".wf");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("French Southern and Antarctic Lands","Territory of the French Southern and Antarctic Lands","Martin-de-Vivi?s","","","",".tf");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Clipperton Island","","","","","",".pf");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Bouvet Island","","","","","",".bv");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Cook Islands","","Avarua","NZD","Dollar","682",".ck");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Niue","","Alofi","NZD","Dollar","683",".nu");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Tokelau","","","NZD","Dollar","690",".tk");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Guernsey","Bailiwick of Guernsey","Saint Peter Port","GGP","Pound","44",".gg");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Isle of Man","","Douglas","IMP","Pound","44",".im");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Jersey","Bailiwick of Jersey","Saint Helier","JEP","Pound","44",".je");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Anguilla","","The Valley","XCD","Dollar","1-264",".ai");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Bermuda","","Hamilton","BMD","Dollar","1-441",".bm");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("British Indian Ocean Territory","","","","","246",".io");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("British Sovereign Base Areas","","Episkopi","CYP","Pound","357","");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("British Virgin Islands","","Road Town","USD","Dollar","1-284",".vg");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Cayman Islands","","George Town","KYD","Dollar","1-345",".ky");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Falkland Islands (Islas Malvinas)","","Stanley","FKP","Pound","500",".fk");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Gibraltar","","Gibraltar","GIP","Pound","350",".gi");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Montserrat","","Plymouth","XCD","Dollar","1-664",".ms");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Pitcairn Islands","","Adamstown","NZD","Dollar","",".pn");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Saint Helena","","Jamestown","SHP","Pound","290",".sh");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("South Georgia and the South Sandwich Islands","","","","","",".gs");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Turks and Caicos Islands","","Grand Turk","USD","Dollar","1-649",".tc");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Northern Mariana Islands","Commonwealth of The Northern Mariana Islands","Saipan","USD","Dollar","1-670",".mp");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Puerto Rico","Commonwealth of Puerto Rico","San Juan","USD","Dollar","1-787 and 1-939",".pr");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("American Samoa","Territory of American Samoa","Pago Pago","USD","Dollar","1-684",".as");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Baker Island","","","","","","");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Guam","Territory of Guam","Hagatna","USD","Dollar","1-671",".gu");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Howland Island","","","","","","");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Jarvis Island","","","","","","");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Johnston Atoll","","","","","","");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Kingman Reef","","","","","","");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Midway Islands","","","","","","");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Navassa Island","","","","","","");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Palmyra Atoll","","","","","","");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("U.S. Virgin Islands","United States Virgin Islands","Charlotte Amalie","USD","Dollar","1-340",".vi");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Wake Island","","","","","","");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Hong Kong","Hong Kong Special Administrative Region","","HKD","Dollar","852",".hk");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Macau","Macau Special Administrative Region","Macau","MOP","Pataca","853",".mo");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Faroe Islands","","Torshavn","DKK","Krone","298",".fo");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Greenland","","Nuuk (Godthab)","DKK","Krone","299",".gl");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("French Guiana","Overseas Region of Guiana","Cayenne","EUR","Euro","594",".gf");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Guadeloupe","Overseas Region of Guadeloupe","Basse-Terre","EUR","Euro","590",".gp");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Martinique","Overseas Region of Martinique","Fort-de-France","EUR","Euro","596",".mq");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Reunion","Overseas Region of Reunion","Saint-Denis","EUR","Euro","262",".re");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Aland","","Mariehamn","EUR","Euro","340",".ax");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Aruba","","Oranjestad","AWG","Guilder","297",".aw");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Netherlands Antilles","","Willemstad","ANG","Guilder","599",".an");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Svalbard","","Longyearbyen","NOK","Krone","47",".sj");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Ascension","","Georgetown","SHP","Pound","247",".ac");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Tristan da Cunha","","Edinburgh","SHP","Pound","290","");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Antarctica","","","","","",".aq");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Kosovo","","Pristina","CSD and EUR","Dinar and Euro","381",".cs and .yu");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Palestinian Territories (Gaza Strip and West Bank)","","Gaza City (Gaza Strip) and Ramallah (West Bank)","ILS","Shekel","970",".ps");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Western Sahara","","El-Aaiun","MAD","Dirham","212",".eh");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Australian Antarctic Territory","","","","","",".aq");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Ross Dependency","","","","","",".aq");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Peter I Island","","","","","",".aq");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("Queen Maud Land","","","","","",".aq");

INSERT INTO demo_country (`name`,`formal_name`,`capital`,`currency_code`,`currency_name`,`phone_prefix`,`tld`) VALUES ("British Antarctic Territory","","","","","",".aq");

